POST http://localhost:9127/register
Content-Type: application/json

{
    "name": "    <script>maxie_h",
    "email": "maxie.jztutl@gmail.fr",
    "password": "!12343hdkFBHdem,fju56G7+8866"
}

###

POST http://localhost:9127/login
Content-Type: application/json

{
    "email": "maxie.h@gmail.fr",
    "password": "!12343hdkFBHdem,fju56G7+8866"
}

###

POST http://localhost:9127/618269aef8438a896bb5e525/commenting
Content-Type: application/json

{
    "title": "this is an actual test",
    "content": "let´s see if it works..."
}